// Hebrew UI chrome strings (EXECUTION_PLAN.md §2.8, docs/contracts/view-model.md).
// Rule: nothing in this file is a historical assertion. Labels, explanations, reasons and banners only;
// every historical word shown to visitors comes from data records via the view model.
// Placeholders use {name} and are filled by format().

export function format(template, values = {}) {
  return String(template).replace(/\{(\w+)\}/g, (match, key) => (Object.hasOwn(values, key) ? String(values[key]) : match));
}

export const strings = Object.freeze({
  lang: "he",
  app: {
    title: "בית שני ההרודיאני — זמן, מקום ומקורות",
    previewTitlePrefix: "[תצוגה מקדימה] ",
    kicker: "עולם חי מבוסס מקורות",
    heading: "בית שני ההרודיאני",
    scope: "לכל אירוע מוצגים מקורותיו ורמת הוודאות שלו",
    modeLabel: { published: "מצב: תוכן זמני — נוסח ונבדק בידי סוכני בינה מלאכותית (סוכן מנסח וסוכן בודק נפרד ועצמאי); לא נבדק בידי מומחה", preview: "מצב: תצוגה מקדימה (ארגז חול)" },
    loading: "טוען נתונים…",
    skipToState: "דלגו לתוכן במצב הנוכחי"
  },
  banner: {
    preview: "תצוגה מקדימה — ארגז חול: תוכן טעון בדיקה, לא מאושר ולא לפרסום",
    previewStrip: "תצוגה מקדימה — לא לפרסום",
    previewDetail: "החומר כאן נוסח בידי סוכני בינה מלאכותית. חלקו עוד לא עבר את בדיקות הפרסום, ושום דבר כאן לא נבדק בהכרח בידי מומחה. אין לצטט או לפרסם אותו.",
    syntheticFixture: "נתוני בדיקה סינתטיים — לא טענה היסטורית",
    previewUnavailable: "מצב תצוגה מקדימה אינו זמין באתר הציבורי",
    unknownMode: "מצב התצוגה שבכתובת אינו מוכר; מוצג רק התוכן שעבר את בדיקות הפרסום."
  },
  previewExplainer: {
    summary: "מהי התצוגה המקדימה?",
    body: "בתצוגה המקדימה אפשר לראות טיוטות של ראיות ואירועים שעדיין לא עברו את בדיקות הפרסום (בדיקה אוטומטית של הנתונים והציטוטים וביקורת ספקנית עצמאית). כל פריט כזה מסומן „טעון בדיקה”, והתצוגה אינה מיועדת לפרסום.",
    link: "פתיחת התצוגה המקדימה",
    backLink: "חזרה לתוכן שפורסם"
  },
  certainty: {
    documented: { label: "מתועד", explanation: "נאמר במפורש במקור ראשוני מתועד ומקוטלג." },
    traditional: { label: "מסורתי", explanation: "מבוסס על מסורת שנמסרה במקור; ראו „זמן המקור” בראיות." },
    archaeological: { label: "ארכאולוגי", explanation: "מוסק מממצא חומרי; למסקנה כזו יש גבולות, והם מצוינים בראיות." },
    reconstructed: { label: "שחזור", explanation: "צירוף של כמה מקורות לתמונה אחת. זו פרשנות של המקורות, לא עדות ישירה." },
    speculative: { label: "השערה", explanation: "השלמה סבירה שלא אומתה. אין להתייחס אליה כעובדה." },
    requires_review: { label: "טעון בדיקה", explanation: "טרם עבר את בדיקות הפרסום. מוצג רק בתצוגה המקדימה ואינו לפרסום." },
    unknown: { label: "רמת ודאות לא ידועה", explanation: "לרשומה אין רמת ודאות מוכרת; יש לבדוק אותה." },
    // R-12 (proposal, owner may change): a neutral prefix; "ודאות: מתועד" over-signalled reliability.
    chipPrefix: "סוג הביסוס:",
    traditionPrefix: "מסורת:",
    // Shown in brackets after the explanation. Only an expert_reviewed record says a person approved its level.
    granted: "רמה זו אושרה בהחלטת אדם",
    grantedProvisional: "רמה זו נקבעה בבדיקה אוטומטית ובביקורת ספקנית עצמאית; לא נבדקה בידי מומחה",
    notGranted: "רמה זו טרם עברה את בדיקות הפרסום",
    previewBadge: "טעון בדיקה"
  },
  // Who checked a published record (data: record.tier; docs/contracts/world-data.md "Tier semantics").
  tier: {
    provisional: {
      chip: "זמני",
      text: "זמני — נוסח בידי סוכן בינה מלאכותית ונבדק בבדיקות אוטומטיות ובידי סוכן בינה מלאכותית נפרד; לא נבדק בידי מומחה",
      explanation: "פריט זמני נוסח בידי סוכן בינה מלאכותית, עבר בדיקות מכניות (תקינות הנתונים ואימות כל ציטוט מול הטקסט) וביקורת ספקנית של סוכן בינה מלאכותית נפרד מזה שניסח אותו. אדם מומחה לא בדק אותו. אם מצאתם בו טעות, דווחו עליה."
    },
    expert_reviewed: {
      chip: "נבדק בידי אדם",
      text: "נבדק בידי אדם — גרסה זו אושרה בהחלטת אדם",
      explanation: "גרסה זו של הרשומה אושרה בהחלטה של אדם, בנוסף לבדיקות האוטומטיות ולביקורת הספקנית."
    },
    label: "בדיקה:"
  },
  lifecycle: {
    drafted: "טיוטה — טרם נבדקה",
    challenged: "נבדקה בביקורת ספקנית (פרטים בהמשך)",
    approved_for_scope: "אושרה בהחלטת אדם",
    rejected: "נדחתה",
    changes_requested: "נדרשו שינויים",
    withdrawn: "נמשכה",
    superseded: "הוחלפה ברשומה אחרת",
    unknown: "מצב בדיקה לא ידוע"
  },
  publication: {
    published: "עבר את בדיקות הפרסום",
    preview_only: "טיוטה — לתצוגה מקדימה בלבד"
  },
  locationBasis: {
    stated: "נאמר במקור",
    inferred: "מוסק",
    unknown: "בסיס המיקום לא צוין"
  },
  spatialStatus: {
    unplaced: "מיקום במרחב לא נקבע",
    drawnPiece: "מצויר בתלת־ממד כחלק משוער",
    topological: "ידועים קשרי מעבר בלבד, ללא מיקום במרחב",
    schematic: "מיקום סכמטי (השערה חזותית)",
    unknown: "מצב מרחבי לא ידוע"
  },
  count: {
    unspecified: "לא מצוין",
    exact: "{value}",
    range: "{min}–{max}"
  },
  timing: {
    sequenceSingle: "שלב {step} מתוך {count}",
    sequenceRange: "שלבים {from}–{to} מתוך {count}",
    sequenceOf: "בסדר הנרטיבי: {name}",
    anchor: {
      near: "סמוך ל־{label} (לפני או אחרי)",
      before: "לפני {label}",
      after: "אחרי {label}",
      at: "בעת {label}"
    },
    noClock: "המקור אינו נותן שעה",
    anchorForStep: "שלב {step}: {text}",
    anchorForStepLabel: "שלב {step} ({label}): {text}",
    clockRange: "{start}–{end} לפי שעון (מתוך הנתונים)",
    separator: " · "
  },
  time: {
    clockLabel: "{time}",
    clockAxis: "שעה",
    sequenceAxis: "סדר העבודה"
  },
  dayType: {
    label: "הנחת צפייה: סוג היום",
    // STRATEGY-2026-10 §7.5: the default view is the ordinary day, shown as a visible, changeable assumption.
    chip: "הנחת צפייה: {label} — ניתן לשנות",
    chipLabel: "שינוי הנחת הצפייה (סוג היום): {label}",
    chipShort: { unspecified: "סוג היום לא נבחר", ordinary: "יום רגיל", festival: "רגל", yom_kippur: "יום הכיפורים" },
    hint: "ברירת המחדל היא יום רגיל. זו הנחה לצורך הצפייה, לא תאריך היסטורי; התאריך בעולם עדיין לא נקבע, ואפשר לבחור סוג יום אחר או „לא נבחר”.",
    basis: "בחירת המבקר (הנחת צפייה)",
    provisional: "הגדרה זמנית — ברירת מחדל שאומצה וניתנת לשינוי",
    provisionalSuffix: "(הגדרה זמנית)",
    values: {
      unspecified: "לא נבחר",
      ordinary: "יום שאינו רגל ואינו יום הכיפורים",
      festival: "רגל",
      yom_kippur: "יום הכיפורים"
    }
  },
  timeline: {
    heading: "ציר הזמן",
    tabsLabel: "בחירת ציר זמן",
    sequenceTab: "סדר העבודה",
    clockTab: "שעה",
    sequenceIntro: "האירועים ממוקמים לפי סדרם בסיפור המקור, לא לפי שעה.",
    sequenceRangeLabel: "שלב ברצף",
    sequenceValueText: "שלב {step} מתוך {count}: {label}",
    prev: "השלב הקודם",
    next: "השלב הבא",
    first: "לשלב הראשון",
    last: "לשלב האחרון",
    stepsListLabel: "שלבי הרצף",
    stepButton: "שלב {step}",
    currentStep: "השלב הנוכחי",
    noSequence: "אין עדיין רצף שעבר את בדיקות הפרסום במצב זה.",
    sequenceSelectLabel: "רצף",
    orderNoteLabel: "על הסדר",
    clockIntro: "ציר שעון של 24 שעות. אירוע מופיע כאן רק אם יש לו שעה בנתונים.",
    clockRangeLabel: "שעת היום",
    jumpsLabel: "קפיצה לשעה",
    prevEvent: "לאירוע המתוארך הקודם",
    nextEvent: "לאירוע המתוארך הבא",
    noClockEvents: "אין בנתונים אירועים עם שעה, ולכן אין נקודות קפיצה לאירועים.",
    play: "הפעלה",
    pause: "השהיה",
    playLabel: "הפעלה אוטומטית של השעון",
    reducedMotion: "ההפעלה האוטומטית כבויה, כי במכשיר הוגדרה העדפה להפחתת תנועה. אפשר לשנות שעה בעזרת המחוון, החיצים ולחצני הקפיצה.",
    clockNotice: "במקור, אירועי פרוסה זו מסודרים לפי סדר ולא לפי שעה",
    clockNoticeDetail: "לכן הם אינם ממוקמים על השעון. אפשר לראות אותם בתצוגת סדר העבודה:",
    switchToSequence: "מעבר לתצוגת סדר העבודה",
    stepEvidence: "ראיות לשלב",
    stepEvidenceLabel: "ראיות לשלב {step}",
    stepEvidenceTitle: "ראיות לשלב {step}: {label}",
    orderEvidence: "ראיות לסדר",
    orderEvidenceTitle: "ראיות לסדר השלבים: {name}",
    sequenceCertainty: "הסדר עצמו:"
  },
  state: {
    heading: "מה קורה בנקודה זו",
    eventsCount: "{count} אירועים בנקודה זו",
    conditionalHeading: "אירועים שאינם מוצגים בהנחת הצפייה הנוכחית",
    unplacedHeading: "אירועים ללא מיקום על השעון"
  },
  empty: {
    titles: {
      no_approved_data: "אין עדיין תוכן שעבר את בדיקות הפרסום",
      no_event_at_time: "אין אירוע בנקודה זו",
      only_unplaced_events: "אירועים מסודרים לפי סדר, לא לפי שעה",
      day_type_not_applicable: "אירועים שאינם מוצגים בהנחת צפייה זו"
    },
    // By publication policy (bundle.publicationPolicy). Neither says content waits for the owner (ADR-002).
    no_approved_data: "אין עדיין תוכן שעבר את בדיקות הפרסום · {pendingCount} רשומות אירוע עדיין לא עברו את כל הבדיקות",
    no_approved_data_automated: "אין עדיין תוכן שעבר את בדיקות הפרסום · {pendingCount} רשומות אירוע ממתינות לבדיקות עצמאיות (בדיקה אוטומטית וביקורת ספקנית)",
    no_approved_data_preview: "אין בנתונים אירועים להצגה, גם לא כטיוטה.",
    no_event_at_time: "בנתונים אין אירוע שחל בנקודה זו. זה מצב תקין: איננו ממלאים חללים בפעילות מומצאת.",
    only_unplaced_events: "במקור, האירועים בפרוסה זו מסודרים לפי סדרם בסיפור ולא לפי שעה, ולכן אינם ממוקמים על השעון. עברו לתצוגת סדר העבודה כדי לראות אותם.",
    day_type_not_applicable: "יש בנקודה זו אירועים שאינם מוצגים בהנחת הצפייה שבחרתם. הסיבה מפורטת לכל אירוע.",
    day_type_not_applicable_editorial: "יש בנקודה זו אירועים שאינם מוצגים בהנחת צפייה זו. ההגבלה היא הנחה עריכתית של הפרויקט, לא טענת המקור.",
    day_type_unspecified: "יש בנקודה זו אירועים שהתצוגה מגבילה לסוגי יום מסוימים. בחרו „הנחת צפייה: סוג היום” כדי לראות אותם, או הציגו אותם בכל זאת."
  },
  // R-01: wording by applicability basis; an editorial filter is never stated as a fact about the world.
  conditionalReasons: {
    DAY_TYPE_NOT_APPLICABLE: {
      editorial_viewing_assumption: "לא מוצג בהנחת צפייה זו (הנחה עריכתית של הפרויקט, לא טענת המקור)",
      source: "לא מוצג בהנחת צפייה זו; לפי הנתונים, ההגבלה נשענת על המקור (ראו הערה)",
      unknown: "לא מוצג בהנחת צפייה זו (בסיס ההגבלה לא צוין בנתונים)"
    },
    DAY_TYPE_UNSPECIFIED: {
      editorial_viewing_assumption: "לא מוצג כל עוד לא נבחר סוג יום (ההגבלה לסוגי יום היא הנחה עריכתית של הפרויקט, לא טענת המקור)",
      source: "לא מוצג כל עוד לא נבחר סוג יום; לפי הנתונים, ההגבלה נשענת על המקור (ראו הערה)",
      unknown: "לא מוצג כל עוד לא נבחר סוג יום (בסיס ההגבלה לא צוין בנתונים)"
    }
  },
  conditionalReveal: {
    show: "הצג בכל זאת", hide: "הסתר", revealedHeading: "מוצג לבקשתכם",
    revealedNotice: {
      editorial_viewing_assumption: "בדרך כלל אינו מוצג בהנחת הצפייה הנוכחית; ההגבלה היא הנחה עריכתית של הפרויקט, לא טענת המקור.",
      source: "בדרך כלל אינו מוצג בהנחת הצפייה הנוכחית; לפי הנתונים ההגבלה נשענת על המקור (ראו הערה).",
      unknown: "בדרך כלל אינו מוצג בהנחת הצפייה הנוכחית (בסיס ההגבלה לא צוין בנתונים)."
    },
    computedFor: "מחושב בהנחת: {dayType} — לא בהנחת סוג היום שבחרתם",
    anchorNotApplied: "עיגון הזמן שבנתונים חל על „{dayType}” בלבד ואינו מוצג כאן; לסוגי יום אחרים המקורות עשויים לתת עיתוי אחר (ראו ראיות)"
  },
  applicabilityBasis: {
    editorial_viewing_assumption: "הנחה עריכתית של הפרויקט",
    source: "לפי המקור",
    unknown: "בסיס לא צוין"
  },
  reasons: {
    SEQUENCE_ONLY_TIMING: "מסודר במקור לפי סדר, לא לפי שעה",
    ANCHOR_UNRESOLVED: "המיקום תלוי בנקודת עיגון שפירושה שנוי במחלוקת",
    DAY_TYPE_NOT_APPLICABLE: "לא מוצג בהנחת צפייה זו",
    DAY_TYPE_UNSPECIFIED: "לא מוצג כל עוד לא נבחר סוג יום"
  },
  event: {
    location: "מקום",
    timing: "עיתוי",
    participants: "משתתפים",
    certainty: "סוג הביסוס",
    locationInferredNotice: "מיקום האירוע מוסק — המקור אינו מציין היכן התרחש האירוע; זהו היסק. ראיות המקום מראות את קיום המקום ושמו, לא שהאירוע התרחש בו.",
    locationEvidence: "ראיות לקיום המקום",
    locationEvidenceTitle: "ראיות לקיום המקום ולשמו: {name}",
    participantRole: "תפקיד:",
    participantCount: "מספר:",
    showEvidence: "הצג ראיות ({count})",
    showEvidenceLabel: "הצג ראיות לאירוע: {title}",
    alternativesHeading: "קריאות חלופיות",
    alternativeUnresolved: "המחלוקת לא הוכרעה — מוצגות כל האפשרויות שנרשמו כאן; ייתכנו קריאות נוספות. אף אחת אינה ברירת מחדל",
    alternativeSelected: "בחרתם אפשרות זו כהנחת צפייה",
    alternativeApprovedDefault: "ברירת מחדל שאושרה בהחלטת אדם",
    alternativeNoChoice: "בלי לבחור (להציג את כל האפשרויות)",
    alternativeShowAll: "אין בחירה בקבוצה זו",
    alternativeCaveat: "הסתייגות:",
    effectLabel: "משמעות:",
    alternativeNotes: "הערות על המחלוקת"
  },
  evidence: {
    dialogTitle: "ראיות: {title}",
    close: "סגירה",
    claim: "הטענה",
    previewStrip: "תצוגה מקדימה — לא לפרסום",
    alternativeUndecided: "לא הוכרע",
    sequenceEvidence: "ראיות לסדר השלבים ({count})",
    alternativeRefLabel: "קריאה חלופית הנוגעת לרשומה זו:",
    staleSummary: "ביקורות קודמות שאינן עדכניות ({count}) — נכתבו על נוסח קודם של הרשומה",
    concernDetails: "הצגת הנימוקים המלאים (באנגלית)",
    claimKind: "סוג הטענה:",
    sourceType: "סוג המקור:",
    rolesLabel: "תפקיד באירוע:",
    roles: { step: "שלב ברצף", timing: "עיתוי (נקודת עיגון)", location: "ביסוס מקום האירוע" },
    claimKinds: {
      event_step: "שלב באירוע", practice: "נוהג", location: "מקום", role: "תפקיד", object: "חפץ", architecture: "אדריכלות",
      access_rule: "כלל גישה", chronology: "כרונולוגיה", sequence_order: "סדר שלבים"
    },
    catalogKinds: {
      modern_reference: "מקור עזר משני (אנציקלופדיה מקוונת או אתר)",
      modern_reconstruction: "שחזור מודרני",
      modern_scholarship: "מחקר מודרני",
      archaeological_publication: "פרסום ארכאולוגי",
      prophetic_vision: "חזון נבואי"
    },
    sourceTypes: {
      rabbinic_tradition: "מסורת רבנית", historical_narrative: "חיבור היסטורי", archaeological: "ממצא ארכאולוגי",
      scripture: "מקרא", modern_scholarship: "מחקר מודרני", modern_reconstruction: "שחזור או סיכום מודרני"
    },
    lifecycle: "מצב בדיקה",
    source: "מקור",
    excerpt: "ציטוט בשפת המקור",
    translation: "תרגום",
    sourceNote: "הערת המקור/המתרגם:",
    sourceNoteEnglish: "הערת המקור/המתרגם (באנגלית):",
    translationOf: "תרגום לאנגלית של {locator} — אינו מוצמד לציטוט מסוים שלמעלה",
    sourcesHeading: "המקורות ברשומה (לפי סדר הרשומה)",
    edition: "מהדורה",
    license: "רישיון",
    otherSources: "מקורות נוספים ברשומה",
    relation: { supports: "תומך", contextualizes: "מספק הקשר", complicates: "מסבך / מערער" },
    excerptRole: { quotation: "ציטוט", translation: "תרגום", summary: "תקציר" },
    interpretation: "פרשנות (מנוסחת באנגלית)",
    notStated: "מה המקור אינו אומר",
    variants: "נוסחים אחרים",
    variantWitness: "עד נוסח",
    variantEffect: "השפעה",
    skeptic: "ביקורת ספקנית",
    skepticNone: "אין ביקורת ספקנית לרשומה זו.",
    skepticStale: "ביקורת זו נכתבה על נוסח קודם של הרשומה (לא עדכנית)",
    skepticCurrent: "ביקורת עדכנית",
    recommendation: {
      ready_for_human_review: "עבר ביקורת עצמאית",
      revise: "דרוש תיקון",
      reject: "לדחות"
    },
    recommendedMax: "רמת ודאות מרבית מומלצת:",
    proposedCertainty: "רמה שהציע המנסח:",
    topConcerns: "הסתייגויות עיקריות",
    moreConcerns: "ועוד {count} הסתייגויות",
    checks: {
      periodMixing: "ערבוב תקופות",
      translationDependence: "תלות בתרגום",
      missingContext: "הקשר חסר",
      architecturalOverreach: "הפרזה אדריכלית",
      competingReadings: "קריאות מתחרות",
      wordingOverreach: "ניסוח מופרז",
      quoteVerification: "אימות ציטוט"
    },
    checkResult: { pass: "תקין", concern: "הסתייגות", fail: "כשל" },
    // M3-02: how the project reached the source. Shown as a chip next to every locator.
    accessMode: {
      search_snippet: "סוכם מתוך תוצאות חיפוש — הדף עצמו לא נקרא",
      page_read: "נקרא מן הדף/הקוד המקורי"
    },
    period: "תקופה",
    periodSource: "זמן המקור",
    periodDescribed: "התקופה המתוארת",
    gapRisk: "סיכון פער זמנים",
    gapRiskValues: { low: "נמוך", medium: "בינוני", high: "גבוה" },
    missing: "הרשומה {id} אינה זמינה במצב זה",
    translationOmitted: "התרגום האנגלי (Kulp) אינו מוצג באתר הציבורי: הרישיון טרם אושר בידי בעל הזכויות",
    englishNote: "טקסט באנגלית מתוך הרשומה",
    attribution: {
      kulp: "תרגום: ד״ר יהושע קולפ, \u2066Mishnah Yomit\u2069; לפי \u2066Sefaria\u2069: \u2066CC-BY\u2069 (הרישיון טרם אושר בידי בעל הזכויות)",
      whiston: "תרגום: ויליאם ויסטון (\u2066Whiston\u2069), הטקסט עצמו בנחלת הכלל; קובץ \u2066Perseus\u2069 ברישיון \u2066CC-BY-SA 4.0\u2069"
    }
  },
  diagnostics: {
    REF_UNKNOWN_ALTERNATIVE: "בחירה בקריאה חלופית לא זוהתה והתעלמנו ממנה; לא הוחלפה באפשרות אחרת.",
    ALTERNATIVE_SELECTION_IGNORED: "בקבוצה זו מוצגות תמיד כל האפשרויות, ולכן הבחירה לא הוחלה.",
    REF_UNKNOWN_SEQUENCE: "הרצף המבוקש אינו קיים במצב זה.",
    PARTICIPANT_CONFLICT: "אותו משתתף מופיע בשני אירועים חופפים; שניהם מוצגים ולא הוכרע ביניהם.",
    ACCESS_DENIED: "כלל גישה אוסר על משתתף להימצא במקום האירוע; הסתירה מוצגת ולא תוקנה.",
    importIssues: "{count} בעיות אימות בנתוני הטיוטה (פרטים ב־npm run validate:world).",
    generic: "התגלתה בעיה בנתונים: {code}"
  },
  error: {
    title: "לא ניתן היה לטעון את הנתונים",
    body: "חלק מקובצי הנתונים לא נטענו או אינם תקינים, ולכן לא מוצג מצב העולם. דבר לא הומצא במקומם.",
    detail: "קובץ: {file}",
    retry: "ניסיון חוזר",
    manifestRejected: "נתיב נתונים חלופי מותר רק תחת ‎/test/fixtures/‎ באותו אתר.",
    stateError: "לא ניתן לחשב את מצב העולם עבור בחירה זו."
  },
  scene: {
    heading: "מרחב",
    placeholder: "תצוגת מרחב תתווסף בשלב מאוחר יותר. בינתיים לא מוצגת שום גאומטריה, כי עדיין אין מיקום מרחבי שעבר את בדיקות הפרסום.",
    locationsHeading: "מקומות בנקודה זו",
    unavailable: "תרשים המקומות אינו זמין כרגע. כל המידע מוצג בתצוגה הטקסטואלית.",
    noEventHere: "אין אירוע פעיל במקום זה בנקודה הנבחרת.",
    inferredLocation: "מיקום מוסק",
    locationEvidenceTitle: "ראיות לקיום המקום ולשמו: {name}",
    edgeEvidenceTitle: "ראיות למעבר: {via}",
    edgeBetween: "בין: {from} · {to}",
    edgesHeading: "מעברים בתרשים",
    edgeEvidence: "ראיות למעבר",
    otherLocations: "מקומות נוספים בנתונים שאינם קשורים לתצוגה זו ({count})",
    chooserTitle: "כמה אירועים פעילים כאן — בחרו אירוע להצגת הראיות:",
    chooserClose: "סגירת הבחירה",
    inspectorLocation: "מקום האירוע:",
    graph: {
      groupLabel: "תרשים קשרים בין המקומות במצב הנוכחי",
      legendTitle: "מקרא",
      legend: {
        diagramNotMap: "זהו תרשים של קשרים בין מקומות, לא מפה: למיקום, למרחק ולגודל אין משמעות.",
        evidenced: "רשומה זמנית שעברה את בדיקות הפרסום",
        provisional: "טיוטה — ממתינה לבדיקה",
        speculative: "השלמה סכמטית משוערת — לא טענה",
        unplaced: "אין למקום מיקום במרחב במקורות — מוצג במגש",
        activeEvent: "אירוע פעיל כאן בנקודה הנבחרת",
        entity: "משתתף באירוע פעיל (המספר אינו מיוצג)",
        schematicNote: "תיבות סכמטיות הן השלמה חזותית בלבד",
        inferredLocation: "מיקום מוסק: המקור אינו מציין שהאירוע התרחש כאן"
      },
      trayTitle: "ללא מיקום במרחב",
      empty: "אין מקומות להצגה במצב זה",
      separator: " · ",
      entityMarker: "משתתף",
      certaintyPrefix: "סוג הביסוס: {level}",
      certainty: {
        documented: "מתועד", traditional: "מסורתי", archaeological: "ארכאולוגי",
        reconstructed: "שחזור", speculative: "השערה", requires_review: "טעון בדיקה"
      },
      treatment: {
        evidenced: "עבר את בדיקות הפרסום",
        provisional: "ממתין לבדיקה",
        speculative: "השלמה משוערת",
        unplaced: "ללא מיקום במרחב"
      },
      publication: { preview_only: "לתצוגה מקדימה בלבד" },
      inferredLocation: "מיקום האירוע מוסק",
      edgeVia: "מעבר:",
      activeEvents: "אירועים פעילים: {count}",
      access: {
        allow: "גישה מותרת לפי כלל (מספר משתתפים: {count})",
        deny: "גישה אסורה לפי כלל (מספר משתתפים: {count})",
        unknown: "גישה לא ידועה (מספר משתתפים: {count}; אין כלל גישה בנתונים)"
      }
    }
  },
  // Feedback dialog (docs/contracts/feedback.md "UI contract"). A report is never presented as a historical claim.
  feedback: {
    report: "דווחו על בעיה",
    reportLabel: "דווחו על בעיה: {subject}",
    generalReport: "דווחו על בעיה או הציעו תיקון",
    generalSubject: "האתר באופן כללי",
    title: "דיווח על בעיה",
    subject: "נושא הדיווח:",
    kinds: {
      event: "אירוע", evidence: "ראיה", location: "מקום", edge: "מעבר בין מקומות", sequence: "רצף", role: "תפקיד", entity: "משתתף",
      alternative_group: "קריאה חלופית", geometry: "חלק בתצוגת המרחב", ui: "ממשק", general: "כללי"
    },
    intro: "הדיווח עוזר לנו לתקן. כל דיווח נבדק מול המקורות לפני שינוי כלשהו בתוכן; הדיווח עצמו אינו נחשב טענה היסטורית.",
    category: "סוג הדיווח (חובה)",
    categories: {
      wrong: "משהו כאן שגוי",
      missing_source: "חסר מקור או שהמקור אינו תומך",
      alternative: "יש קריאה או פרשנות חלופית",
      ui: "בעיה בממשק (תצוגה, ניווט, נגישות)",
      other: "אחר"
    },
    message: "תיאור (חובה)",
    messageHint: "מה לא נכון או חסר? אם אפשר, ציינו מקור ומקום מדויק בו.",
    counter: "{count} / {max} תווים",
    sourceSuggestion: "הצעת מקור (רשות)",
    sourceSuggestionHint: "למשל: חיבור, פרק ופסוק או עמוד. שורה אחת.",
    contact: "פרטי קשר (רשות)",
    contactHint: "רק אם תרצו שנחזור אליכם. נשמרים בנפרד מהדיווח ואינם מוצגים איתו.",
    autoData: "יחד עם הדיווח נשמרים אוטומטית כתובת העמוד (בלי פרמטרים אחרים) וגודל החלון, כדי שנוכל לשחזר את התצוגה. לא נאסף מידע אישי אחר.",
    submit: "שליחת הדיווח",
    sending: "שולח…",
    cancel: "ביטול",
    close: "סגירה",
    required: {
      category: "בחרו את סוג הדיווח.",
      message: "כתבו תיאור קצר של הבעיה."
    },
    tooLong: "הטקסט ארוך מהמותר ({max} תווים).",
    fieldInvalid: "השדה לא התקבל: יש בו תווים שאינם מותרים או שהוא ארוך מדי.",
    fieldErrorsSummary: "הדיווח לא נשלח: יש לתקן את השדות המסומנים.",
    success: "תודה! הדיווח התקבל.",
    successId: "מזהה הדיווח: {id}",
    successNext: "נבדוק אותו מול המקורות. התוכן באתר לא ישתנה עד שהדיווח ייבדק.",
    retryLater: {
      413: "הדיווח גדול מדי לשליחה. קצרו את הטקסט ונסו שוב, או שמרו אותו בדרך שלמטה.",
      429: "נשלחו דיווחים רבים מדי בזמן קצר. נסו שוב בעוד דקה, או שמרו את הדיווח בדרך שלמטה."
    },
    fallbackTitle: "הדיווח לא נשלח",
    publicBuildLead: "האתר הציבורי הוא אתר סטטי ואינו מקבל דיווחים ישירות.",
    fallbackBody: "לא ניתן היה לשלוח את הדיווח מכאן (ייתכן שהאתר מוגש כאתר סטטי או שהשרת אינו זמין). דבר ממה שכתבתם לא אבד: הטקסט נשאר בטופס, ואפשר לשמור אותו כקובץ או להעתיק אותו.",
    fallbackWhere: "שלחו את הקובץ או את הטקסט לצוות הפרויקט בערוץ שבו קיבלתם את הקישור לאתר.",
    download: "הורדה כקובץ",
    copy: "העתקה",
    copied: "הטקסט הועתק. הדיווח עדיין לא נשלח — הדביקו אותו בהודעה לצוות הפרויקט.",
    copyFailed: "ההעתקה האוטומטית לא הצליחה. סמנו את הטקסט שבתיבה והעתיקו אותו ידנית.",
    downloaded: "הקובץ נשמר. הדיווח עדיין לא נשלח — צרפו את הקובץ להודעה לצוות הפרויקט.",
    plainText: {
      header: "דיווח על בעיה (לא נשלח אוטומטית)",
      subject: "נושא",
      category: "סוג",
      message: "תיאור",
      sourceSuggestion: "הצעת מקור",
      contact: "פרטי קשר",
      page: "עמוד",
      viewport: "גודל חלון"
    },
    copyTextLabel: "טקסט הדיווח להעתקה"
  },
  // 3D view (TASK-6-19; docs/scene/3d-architecture.md §4.1). UI chrome only: every place name, number and note comes
  // from geometry/evidence/alternative records.
  scene3d: {
    toggle: "תצוגה תלת־ממדית",
    toggleHide: "הסתרת התצוגה התלת־ממדית",
    heading: "תלת־ממד",
    intro: "תרשים סכמטי של המידות הנזכרות במקורות — לא שחזור של מראה המקדש. תיבות לפי מידות שבמקורות, ובהן השלמות רבות (מסומנות); אין בו חומרים, עיטורים או צורות מדויקות. מיקומי המקומות כאן הם השלמות של התרשים; בתרשים הקשרים הם מסומנים „ללא מיקום במרחב”.",
    tierChip: "זמני",
    tierStatement: "כל חלקי התרשים זמניים: נוסחו ונבדקו בידי סוכני בינה מלאכותית (סוכן מנסח וסוכן בודק נפרד); לא נבדקו בידי מומחה.",
    amahChipAssumed: "יחידת המידה: אמה ≈ {cm} ס״מ (הנחה) — שינוי",
    amahChipChosen: "יחידת המידה: אמה ≈ {cm} ס״מ (בחירתכם) — שינוי",
    moreAssumptions: "ועוד {count} הנחות צפייה",
    moreAssumptionsOne: "ועוד הנחת צפייה אחת",
    access: { allowed: "מותר", forbidden: "אסור", no_source: "אין מקור במערכת" },
    persona: {
      heading: "מי אתם?",
      intro: "בחירת תפקיד מציגה מה אומרים כללי הגישה שברשומות לגבי כל מקום. מקום שאין לו כלל מקור מסומן „אין מקור במערכת” — אין כאן השערה.",
      selectLabel: "מי אתם?",
      none: "לא נבחר",
      status: { allowed: "מותר", forbidden: "אסור", no_source: "אין מקור במערכת" },
      ruleEffect: { allow: "מותר", deny: "אסור" },
      summary: "בתצוגה התלת־ממדית: {forbidden} חלקים אסורים, {allowed} מותרים, {no_source} ללא מקור.",
      dimNote: "הסימון בתצוגה התלת־ממדית ובמקרא: מותר — צבוע בירוק; אסור — מועמעם מאוד; ללא מקור — מועמעם מעט (אין בכך קביעה שהוא מותר).",
      caption: "התפקיד שנבחר: {name}",
      legendHeading: "מקרא סימון הגישה",
      legend: { allowed: "מותר — צבע ירקרק", forbidden: "אסור — מועמעם מאוד, כמעט שקוף", no_source: "אין מקור במערכת — מועמעם מעט, לא נקבע שהוא מותר" },
      evidenceButton: "ראיות לכלל",
      evidenceDialogTitle: "ראיות לכלל הגישה: {rule}",
      noEvidence: "אין ראיות מקושרות לכלל זה.",
      pieces: "חלקים מצוירים במקום זה: {count}",
      noPieces: "אין חלק מצויר המקושר למקום זה, ולכן אין מה לסמן בתלת־ממד.",
      conditional: "קיים כלל מותנה (טהרה או זמן) שאינו נבדק כאן.",
      rule: "הכלל:",
      source: "מקור:",
      exteriorNone: "ל־{count} חלקי המתחם החיצוני (חלקים שמוצגים רק באפשרויות מסוימות של הר הבית) אין כלל גישה במערכת; לכן הם מסומנים „אין מקור במערכת” ואין כאן השערה.",
      noRulesHeading: "מקומות ללא כלל",
      rulesHeading: "כללי הגישה לפי מקום"
    },
    otherViewNote: "בתצוגה התלת־ממדית מוצג מיקום משוער (השלמה של התרשים)",
    otherViewOpen: "הצגה בתלת־ממד",
    loading: "טוען את התצוגה התלת־ממדית…",
    unavailable: "התצוגה התלת־ממדית אינה זמינה בדפדפן זה (אין תמיכה ב־WebGL). תרשים הקשרים והתצוגה הטקסטואלית ממשיכים לעבוד במלואם.",
    failed: "התצוגה התלת־ממדית לא נטענה. תרשים הקשרים והתצוגה הטקסטואלית ממשיכים לעבוד במלואם.",
    emptyPublished: "אין עדיין חלקים שעברו את בדיקות הפרסום.",
    modeLabel: "אופן צפייה",
    overview: "מבט אלכסוני",
    plan: "תכנית מלמעלה",
    planLabel: "תצוגת תכנית: מבט ישר מלמעלה, להשוואת קווי המתאר",
    walk: "הליכה",
    helpSummary: "מקשים",
    help: "בתוך התמונה: [ ו־] — מעבר בין חלקים, Enter — פתיחת פרטי החלק. מבט אלכסוני ותכנית: חיצים — סיבוב, + ו־- — קירוב והרחקה, Home — מבט מלא. הליכה: W/S או חיצים — קדימה ואחורה, A/D — צעד לצד, Q/E — פנייה, Esc — חזרה למבט האלכסוני.",
    reducedMotion: "הוגדרה העדפה להפחתת תנועה: המצלמה זזה בלי האטה מונפשת.",
    canvasLabel: "מודל תלת־ממדי. [ ו־] מעבר בין חלקים, Enter לפתיחת פרטים",
    listLabel: "חלקי המודל",
    listTitle: "חלקי המודל (אפשר לבחור גם מכאן)",
    markers: {
      countCapped: "מוצגות {shown} מתוך {total}",
      countUnspecified: "מספר לא נאמר במקור",
      groupUnspecified: "קבוצה — מספר לא נאמר במקור",
      enlarged: "מוגדל לשם קריאות",
      conditional: "מותנה",
      position: "המיקום והגובה בתוך החלק — בחירת תצוגה",
      locationInferred: "מקום האירוע מוסק"
    },
    legendTitle: "מקרא",
    legendNote: "תרשים מן המקורות, לא שחזור. חלקים שקופים ומקווקווים הם השלמה חזותית.",
    legend: {
      sourced: "מידה מן המקור",
      alternative: "מידה לפי חלופה שנבחרה (יש מקורות חלוקים)",
      speculative: "השלמה חזותית — לא מידה מן המקור",
      assumed: "מוצג לפי הנחת צפייה שלא נבחרה בידיכם",
      // TASK-6-24 renderer legend (two channels: fill = size basis, outline = position basis).
      sizeSourced: "מילוי אחיד — המידה מן המקור",
      sizeAlternative: "מילוי מנוקד — המידה לפי הקריאה שנבחרה",
      sizeSpeculative: "מילוי שקוף מקווקו — המידה היא השלמה חזותית",
      placementStated: "קו מתאר רציף — המיקום נאמר במקור",
      placementCompletion: "קו מתאר מקוטע — המיקום הוא השלמה או נקודת המוצא של התרשים",
      // TASK-6-57 presentation legend (ADR-004): the edge pattern and the opacity carry certainty, never colour alone.
      presentationSourced: "קו מתאר רציף — מידה מן המקור",
      presentationAlternative: "קו מנוקד — מידה לפי חלופה שנבחרה",
      presentationSpeculative: "בהיר ושקוף למחצה, קו מקווקו — השלמה חזותית (השערה), לא מידה מן המקור"
    },
    basis: {
      plan: { sourced: "תכנית: מן המקור", alternative: "תכנית: לפי הקריאה שנבחרה", speculative: "תכנית: השלמה" },
      height: { sourced: "גובה: מן המקור", alternative: "גובה: לפי הקריאה שנבחרה", speculative: "גובה: השלמה" },
      placement: { stated: "מיקום: נאמר במקור", completion: "מיקום: השלמה", origin: "מיקום: נקודת המוצא של התרשים (לא טענה)" }
    },
    recordedNotDrawn: "מחלוקת הנוגעת לחלק זה; התרשים אינו מבחין בין האפשרויות. האפשרויות שנרשמו:",
    conflicts: {
      NOT_CONTAINED: "בבחירות אלה {label} חורג מתחום {of}{sides} — המידות אינן מתיישבות זו עם זו."
    },
    conflictSides: " (לכיוון {sides})",
    sideNames: { east: "מזרח", west: "מערב", north: "צפון", south: "דרום" },
    conflictsHeading: "סתירות בבחירות הנוכחיות",
    middotDefault: "כברירת מחדל התרשים עוקב אחר משנה מידות; ניתן לבחור חלופות.",
    framingAll: "הצג את כל הר הבית",
    framingFocus: "התמקדות במתחם הפנימי",
    certaintyStyle: { sourced: "מידה מן המקור", alternative: "לפי חלופה", speculative: "השלמה חזותית" },
    assumed: "מוצג לפי הנחה שלא נבחרה",
    assumedShort: "(הנחה)",
    kind: { platform: "רחבה", court: "עזרה", wall: "קיר", gate: "שער", building: "מבנה", altar: "מזבח", barrier: "גדר", portico: "אכסדרה", stair: "מדרגות" },
    porticoThinned: "לשם ביצועים מוצגים {drawn} מתוך {total} העמודים",
    empty: "אין חלקים להצגה",
    walkHint: "מצב הליכה. Esc לחזרה למבט האלכסוני.",
    overviewHint: "מצב מבט אלכסוני.",
    separator: " · ",
    assumptionsHeading: "חלופות",
    alternativesIntro: "בחרו קריאה לכל מחלוקת; הבחירה משנה את השרטוט ואת הרשימה הטקסטואלית ונשמרת בכתובת הדף. כל עוד לא בחרתם, מוצגת הנחת צפייה.",
    selectableHeading: "חלופות לבחירה",
    shownTogetherHeading: "מוצגות יחד",
    shownTogetherNote: "בקבוצות אלה אין בחירה: כל האפשרויות מוצגות יחד.",
    notUsedNote: "בחירה זו אינה משפיעה על החלקים המשורטטים כעת.",
    optionEvidence: "מקור:",
    optionDetails: "פירוט האפשרויות והמקורות",
    assumedDepends: "תלוי בהנחת צפייה: {questions}",
    assumedNotice: "מוצג לפי הנחה: {option} — בחרו חלופה",
    commonAssumedNotice: "כל חלקי התרשים תלויים בהנחת צפייה אחת לפחות שלא נבחרה: {questions}. הסימון „(הנחה)” ליד חלק מציין הנחות נוספות, מיוחדות לאותו חלק.",
    chosenNotice: "מוצג לפי בחירתכם: {option}",
    showAllNotice: "מוצג לפי האפשרות הראשונה ברשימה ({option}) לצורך השרטוט בלבד; בקבוצה זו אין בחירה, וכל האפשרויות מוצגות:",
    usedBy: "משמש ב־{count} חלקים",
    usedByOne: "משמש בחלק אחד",
    chooseLabel: "בחירת חלופה: {question}",
    notChosenOption: "לא נבחר (מוצג לפי הנחה)",
    notShownHeading: "חלקים שאינם מוצגים באפשרות הנבחרת",
    notShownIntro: "לחלקים אלה יש נתונים רק לאפשרויות אחרות של אחת החלופות; הם אינם מוצגים כאן, ואין זו טענה שלא היו.",
    notShownItem: "{label} — אינו מוצג באפשרות זו; מוצג רק ב: {options}",
    notShownLine: "{label} — אינו מוצג באפשרות הנוכחית ({current})",
    notShownLineNoCurrent: "{label} — אינו מוצג באפשרות הנוכחית",
    notShownOptions: "באילו אפשרויות מוצג",
    notShownSummary: "{count} חלקים אינם מוצגים באפשרות זו",
    notShownShownIn: "מוצג ב: {options}",
    unresolvedHeading: "חלקים שלא ניתן לשרטט",
    unresolvedReason: {
      UNIT_NOT_CONVERTIBLE: "לא ניתן לשרטט: {label} — יחידת מידה ללא המרה מבוססת ({unit})",
      UNIT_NOT_CONVERTIBLE_choose: "לא ניתן לשרטט: {label} — יחידת מידה ללא המרה מבוססת ({unit}). אפשר לבחור המרה מתועדת:",
      MISSING_DIMENSION: "לא ניתן לשרטט: {label} — חסרה מידה",
      PARENT_UNRESOLVED: "לא ניתן לשרטט: {label} — תלוי בחלק שלא שורטט",
      REF_MISSING: "לא ניתן לשרטט: {label} — הפניה לחלק שאינו קיים",
      CYCLE: "לא ניתן לשרטט: {label} — תלות מעגלית במיקום",
      SELECTION_MISSING: "לא ניתן לשרטט: {label} — אין אפשרות בקבוצת החלופות",
      INVALID_DIMENSION: "לא ניתן לשרטט: {label} — מידה לא תקינה",
      PLACEMENT_INVALID: "לא ניתן לשרטט: {label} — יחס מיקום לא מוכר",
      generic: "לא ניתן לשרטט: {label} ({reason})"
    },
    unitsPlural: { amah: "אמות", tefach: "טפחים", etzba: "אצבעות", kaneh: "קנים", cubit_greek: "אמות יווניות (פכיס)", pous: "רגליים (פוס)", plethron: "פלתרונים", stadion: "אצטדיונים", metre: "מטרים", centimetre: "ס״מ" },
    units: { amah: "אמה", tefach: "טפח", etzba: "אצבע", kaneh: "קנה", cubit_greek: "אמה יוונית (פכיס)", pous: "רגל (פוס)", plethron: "פלתרון", stadion: "אצטדיון", metre: "מטר", centimetre: "ס״מ" },
    inspector: {
      accessHeading: "גישה לפי התפקיד שנבחר",
      accessLine: "עבור „{persona}”:",
      accessRule: "הכלל:",
      title: "חלק במודל: {label}",
      sizeHeading: "מידות",
      placementHeading: "מיקום",
      dimension: { length: "אורך (מזרח–מערב)", width: "רוחב (צפון–דרום)", height: "גובה", thickness: "עובי",
        depth: "עומק (רוחב האכסדרה)", spacing: "מרווח בין עמודים", rows: "מספר שורות עמודים", columns: "מספר עמודים בשורה", steps: "מספר מדרגות" },
      appliesOnly: "חלק זה מוצג רק באפשרויות: {options}. באפשרויות אחרות הוא אינו מוצג (אין זו טענה שלא היה).",
      porticoThinned: "לשם ביצועים השרטוט מציג {drawn} מתוך {total} העמודים; המספר במודל הוא {total}.",
      dimensionNorthSouth: { length: "אורך (צפון–דרום)", thickness: "עובי (מזרח–מערב)" },
      distanceFrom: { north: "מרחק מן הצפון", south: "מרחק מן הדרום", east: "מרחק מן המזרח", west: "מרחק מן המערב" },
      value: "{value} {unit}",
      metres: "≈ {metres} מ׳",
      amahRange: "(≈ {low}–{high} מ׳ לפי אורך האמה)",
      noteMissing: "השלמה חזותית — הנתונים אינם מסבירים מספר זה",
      derivedFrom: "נגזר מ:",
      relationText: "{relation}: {of}",
      placementRootStyle: "מיקום: נקודת המוצא של התרשים (לא טענה)",
      axesHeading: "מה קובע את המיקום בכל ציר:",
      axis: { x: "מזרח–מערב", y: "גובה", z: "צפון–דרום" },
      axisBasis: { sourced: "נאמר במקור", alternative: "לפי הקריאה שנבחרה", speculative: "השערה", solver_default: "השלמה של התרשים (מירכוז או צמידות)", origin: "נקודת המוצא (לא טענה)" },
      planStyle: "תכנית:",
      heightStyle: "גובה:",
      placementEvidencePartial: "היחס מן המקור; המרחק או הציר השני — השלמה",
      notSwitchable: "מחלוקת שנרשמה בראיות: {question} — חלופה זו עדיין אינה ניתנת להחלפה בתצוגה; המידות כאן לפי הרשומות שמופיעות בחלק.",
      source: { evidence: "מן המקור", alternative: "לפי חלופה", speculative: "השערה" },
      sourceLabel: "מקור:",
      noSourceNote: "השערה — אין מידה במקור:",
      heightUnstated: "השערה — המקור אינו נותן גובה; מוצג עובי סמלי",
      conversion: "המרה למטרים לפי: {option}",
      conversionAssumed: "(הנחת צפייה — לא נבחרה בידיכם)",
      displayConversion: "המרת יחידה לתצוגה: {text}",
      alternative: "חלופה: {question} — {option}",
      sizeStyle: "סוג המידות:",
      placementStyle: "סוג המיקום:",
      relation: { inside: "בתוך", centered_on: "ממורכז על", east_of: "ממזרח ל", west_of: "ממערב ל", north_of: "מצפון ל", south_of: "מדרום ל", adjoins: "צמוד ל" },
      root: "נקודת המוצא של המודל",
      placementSource: { root: "נקודת מוצא", evidence: "מן המקור", speculative: "השערה" },
      defaults: {
        centred_in_parent: "ממורכז בתוך החלק המכיל (השלמה)",
        cross_axis_centred: "ממורכז בציר השני (השלמה)",
        offset_unstated: "המרחק אינו נאמר במקור (השלמה)",
        side_unstated: "הצד אינו נאמר במקור (השלמה)",
        root_at_origin: "הוצב בנקודת המוצא (השלמה)",
        segment_centred: "ממורכז לאורך הצלע (השלמה)"
      },
      unknownDefault: "השלמה של התרשים",
      offset: "מרחק:",
      speculativePrefix: "השערה:",
      speculativeValue: "ערך חזותי בלבד",
      outlineHeading: "אורכי ארבע הצלעות של קו המתאר המשורטט",
      outlineSide: { west: "צלע מערבית", east: "צלע מזרחית", north: "צלע צפונית", south: "צלע דרומית" },
      outlineConstruction: "איך נסגר המרובע:",
      alternativesHeading: "חלופות הנוגעות לחלק זה",
      eventsHeading: "אירועים פעילים במקום זה בנקודה הנבחרת",
      noEvents: "אין אירוע פעיל במקום זה בנקודה הנבחרת.",
      openEvent: "הצג את האירוע: {title}",
      evidenceHeading: "ראיות לחלק זה"
    }
  },
  // Guided tour (TASK-6-47). Chrome only: every stop's content (titles, notes, names, locations) comes from data.
  tour: {
    heading: "סיור: עבודת הבוקר",
    intro: "סיור מודרך בשלבי הרצפים הרשומים בנתונים, שלב אחר שלב. בכל שלב מוצגים האירוע, מקורו ומידת הביסוס שלו, ואפשר לפתוח את הראיות שלו. הסדר הוא סדר הסיפור במשנה, לא שעות.",
    start: "התחלת הסיור",
    exit: "יציאה מהסיור",
    prev: "השלב הקודם",
    next: "השלב הבא",
    controlsLabel: "בקרת הסיור",
    indicator: "שלב {n} מתוך {total}",
    live: "שלב {n} מתוך {total}: {title}",
    sequenceLabel: "רצף:",
    continuationHeading: "המשך מהרצף הקודם",
    inferredLocation: "מיקום מוסק",
    pieceLine: "חלק בתלת־ממד: {names}",
    noPiece: "למקום זה אין עדיין חלק בתלת־ממד",
    pieceNotShown: "החלק של מקום זה אינו מוצג כרגע בתלת־ממד",
    open3d: "הצגה בתלת־ממד",
    open3dHint: "אפשר לפתוח את התצוגה התלת־ממדית כדי לראות את המקום; הסיור בטקסט שלמעלה מלא בלעדיה.",
    stopsSummary: "רשימת השלבים ({total})",
    stopsLabel: "שלבי הסיור",
    stopItem: "{n}. {title}",
    keyHint: "מקשי החצים עוברים בין השלבים (חץ שמאלה — השלב הבא, חץ ימינה — הקודם); Esc — יציאה מהסיור. במסך מגע אפשר להחליק הצידה.",
    computedFor: "השלב מחושב בהנחת סוג היום: {dayType}",
    unavailable: "לא ניתן להציג את השלב הזה.",
    barLabel: "בקרת הסיור ליד התצוגה התלת־ממדית",
    sameAsPrevious: "אותו מקום כמו בשלב הקודם",
    open3dUnavailable: "התצוגה התלת־ממדית אינה זמינה בדפדפן זה; הסיור בטקסט מלא בלעדיה.",
    endTitle: "סוף השלבים שבמערכת",
    // The range is derived from the published records' locators (tour.js); nothing here names a mishnah.
    endBodyRange: "הסיור מסתיים בשלב האחרון שפורסם. הרשומות מכסות את {tractate} {range}. השלבים שאחריו עדיין אינם במערכת.",
    endBodyComplete: "הסיור מסתיים בשלב האחרון שפורסם. הרשומות מכסות את {tractate} {range}: עבודת הבוקר כפי ש{tractate} מספרת אותה נרשמה כאן עד סופה. קטעים שלא נרשמו אינם בסיור.",
    endExcluded: "{range} (לא כולל {passages})",
    endBodyNoLocator: "הסיור מסתיים בשלב האחרון שפורסם. השלבים שאחריו עדיין אינם במערכת.",
    chapterLabel: "פרק",
    chapterControl: "מעבר לפרק במשנה",
    chapterOption: "פרק {label}",
    conditionalHighPriest: "מותנה: כהן גדול",
    conditionalShabbat: "מותנה: שבת",
    conditionalShabbatVariant: "בשבת: נוסח שבת של שלב זה",
    conditionalOther: "מותנה",
    conditionalHighPriestPartial: "מותנה בחלקו: כהן גדול",
    conditionalShabbatPartial: "מותנה בחלקו: שבת",
    conditionalOtherPartial: "מותנה בחלקו",
    conditionalHighPriestDescribed: "מתואר בהשתתפות כהן גדול — לא נאמר אם גם בלעדיו",
    conditionalNoteHighPriestDescribed: "לפי הרשומה, המשנה מתארת שלב זה בהשתתפות הכהן הגדול ואינה אומרת אם הוא נעשה גם בלעדיו; אינו מוצג כמהלך היומי הרגיל.",
    conditionalNoteHighPriestParticipant: "לפי הרשומה, הכהן הגדול משתתף בשלב זה; אינו מוצג כמהלך היומי הרגיל.",
    conditionalNoteHighPriest: "לפי המשנה, שלב זה נעשה רק כשהכהן הגדול משתתף; אינו מוצג כמהלך היומי הרגיל.",
    conditionalNoteShabbat: "לפי המשנה, שלב זה נעשה בשבת בלבד; אינו מוצג כמהלך היומי הרגיל.",
    conditionalNoteShabbatVariant: "לפי משנה תמיד זהו אותו שלב בסדר הבוקר האחד; בשבת: {detail}.",
    conditionalNoteOther: "לפי הרשומה, שלב זה מותנה; אינו מוצג כמהלך היומי הרגיל.",
    conditionalNotePartialHighPriest: "לפי הרשומה, חלק מן השלב מותנה בכהן הגדול; ראו את פרטי השלב.",
    conditionalNotePartialShabbat: "לפי הרשומה, חלק מן השלב מותנה בשבת; ראו את פרטי השלב.",
    conditionalNotePartialOther: "לפי הרשומה, חלק מן השלב מותנה; ראו את פרטי השלב.",
    continuationFrom: "ממשיך את: {previous}",
    barDetails: "פרטי השלב והראיות"
  },
  // Presentation mode (TASK-6-57, ADR-004): full-screen 3D walkthrough. Chrome only; every historical string comes from data.
  present: {
    open: "מצב הצגה: סיור בתלת־ממד",
    openHint: "מסך מלא, מוכן להקרנה",
    regionLabel: "מצב הצגה",
    loading: "טוען את התצוגה התלת־ממדית…",
    failed: "התצוגה התלת־ממדית לא נטענה. אפשר לחזור לדף הרגיל.",
    exit: "יציאה",
    more: "עוד",
    less: "פחות",
    fullscreen: "מסך מלא",
    fullscreenExit: "יציאה ממסך מלא",
    exitLabel: "יציאה ממצב הצגה",
    materialChip: "מראה החומרים: המחשה, לא טענה",
    markersLegendTitle: "דמויות",
    markersLegend: "סימון מופשט של בעלי התפקיד באירוע. אין בהן לבוש, תנוחה או מספר; הצבע מבחין בין תפקידים בלבד. המיקום והגובה בתוך החלק הם בחירת תצוגה, וכשהמבט רחוק הדמויות עשויות להיות מוגדלות לשם קריאות, ואינן קנה מידה. עיגול שקוף מתחת לדמות מסמן קבוצה שמספרה לא נאמר במקור.",
    materialExplain: "הגוונים והמרקמים בתמונה נועדו להמחשה בלבד: אין כאן טענה על חומר, צבע או עיטור מסוימים. מידת הוודאות של כל חלק מסומנת בסגנון הקו ובשקיפות, לא בצבע.",
    certaintyToggle: "שכבת ודאות",
    certaintyToggleHint: "מחליפה את המראה המוחשי בסימון הוודאות של כל חלק",
    alternatives: "חלופות",
    alternativesWarn: "חלופות — יש סתירה בבחירות",
    legend: "מקרא",
    legendTitle: "מקרא ומראה החומרים",
    pieces: "חלקי המודל",
    piecesHint: "רשימה לבחירת חלק בלי עכבר",
    close: "סגירה",
    provisionalToggle: "מה פירוש „זמני”?",
    previewStrip: "תצוגה מקדימה — לא לפרסום",
    startTitle: "סיור: עבודת הבוקר",
    startBody: "סיור מודרך בן {total} שלבים לפי הרצפים הרשומים בנתונים. בכל שלב: האירוע, מקורו ומידת הביסוס שלו. הסדר הוא סדר הסיפור במשנה, לא שעות.",
    // T-03: a standing line on the tour card; the stage and continuation notes themselves come from the records.
    orderLine: "הסדר הוא סדר הסיפור במשנה, לא שעות. ראיות לסדר השלבים — ב„פרטים”.",
    startExplore: "אפשר גם לסייר בעצמכם: גררו לסיבוב, צבטו או גללו לקירוב, ולחצו על חלק כדי לפתוח את מקורותיו.",
    keyHelp: "מקלדת: Tab עובר בין הפקדים; חצים — השלב הקודם והבא בסיור (שמאלה — הבא); בתצוגה החופשית חצים מסובבים ו־+ ו־- מקרבים; [ ו־] עוברים בין חלקים, Enter פותח את פרטיו; Esc סוגר חלון ואחריו יוצא ממצב הצגה.",
    attribution: "לפי {locator}",
    noAttribution: "מקור: ראו פרטים",
    locationLabel: "מיקום",
    details: "פרטים",
    detailsLabel: "פרטי השלב והראיות",
    prev: "הקודם",
    next: "הבא",
    endTour: "סיום הסיור",
    progressLabel: "התקדמות בסיור",
    keyHint: "חצים: שלב קודם והבא",
    unplacedNote: "מקום זה אינו מצויר במודל. המצלמה מראה מבט כללי, לא את מקום האירוע.",
    unplacedArea: "מקום זה אינו מצויר במודל. המצלמה מראה את {area}, שהמקור מקשר אליו, לא את מקום האירוע.",
    labelInferred: "מקום האירוע מוסק",
    // End card (TASK-6-58): says where the recorded steps stop. The range is what the published records cover.
    endCardTitle: "סוף הסיור",
    // {tractate} {range} come from the published records' locators (tour.js); nothing here names a mishnah.
    endCardRange: "זה סוף השלבים שברשומות: {tractate} {range}. השלבים הבאים עדיין אינם במערכת.",
    endCardComplete: "זה סוף השלבים שברשומות: {tractate} {range}. עבודת הבוקר כפי ש{tractate} מספרת אותה נרשמה כאן עד סופה; קטעים שלא נרשמו אינם בסיור.",
    // T-10: the passages the records cite that are not a stop of their own ({passages} is derived, tour.js excludedPassages).
    endCardExcluded: "{range} (לא כולל {passages})",
    endCardNoRange: "זה סוף השלבים שברשומות. השלבים הבאים עדיין אינם במערכת.",
    chapterShort: "פרק",
    backToOverview: "חזרה למבט כללי",
    backToLive: "חזרה לבוקר החי",
  },
  // M6 live mode (ADR-005). Chrome only: every event, role, action and locator shown in live mode comes from the records.
  live: {
    regionLabel: "הבוקר החי",
    hudLabel: "הפעלת הבוקר החי",
    // ADR-005 D5: never hidden in live mode, beside the material chip.
    motionChip: "תנועה, מסלולים, דמויות, משכים, אש ועשן: המחשה, לא טענה",
    play: "הפעלה",
    pause: "השהיה",
    playLabel: "הפעלת הבוקר",
    pauseLabel: "השהיית הבוקר",
    speedLabel: "מהירות ההצגה",
    speedOption: "×{speed}",
    scrubLabel: "מיקום בסדר העבודה",
    position: "שלב {n} מתוך {total}",
    positionShort: "{n}/{total}",
    ended: "סוף השלבים שברשומות. „הפעלה” מתחילה שוב.",
    durationNote: "לכל שלב ניתן כאן אותו משך, לשם התצוגה בלבד. המקורות אינם נותנים משכים או שעות; הסדר הוא סדר הסיפור במשנה.",
    goToAction: "אל האירוע",
    goToActionHint: "מעבר אל מקום האירוע הפעיל",
    goToActionNone: "האירוע שעכשיו אינו מצויר במודל, ולכן אין לאן לעבור.",
    goToActionBlocked: "המקום הזה אסור לפי כלל הגישה עבור התפקיד שבחרתם, ולכן אין מעבר אליו.",
    bubbles: "תוויות",
    bubblesLabel: "הצגת תוויות הרקע מעל הדמויות",
    menu: "תפריט",
    menuTitle: "תפריט הבוקר החי",
    tour: "סיור מודרך",
    tourHint: "מעבר לסיור שלב אחר שלב, עם כל פרטי המקורות",
    page: "דף הטקסט",
    pageHint: "כל השלבים והמקורות כטקסט",
    personaLabel: "מי אתם?",
    personaNone: "מבקרים (לא נבחר תפקיד)",
    personaNote: "בחירת תפקיד מפעילה את כללי הגישה שברשומות: מעבר למקום שהכלל אוסר נחסם, ומקום ללא כלל אינו נבדק.",
    gateBlocked: "המעבר נחסם: לפי כלל הגישה, „{place}” אסור עבור „{persona}”.",
    gateInside: "אתם בתוך מקום שכלל הגישה אוסר עבור „{persona}”: „{place}”.",
    gateConditional: "ל„{place}” יש כלל גישה מותנה עבור „{persona}” (טהרה או זמן), שאינו נבדק כאן.",
    gateEvidence: "מקור הכלל",
    gateDismiss: "סגירה",
    walkHint: "תנועה: חצים או WASD (Shift — מהר); גררו כדי להסתכל. במגע: גררו בצד שמאל כדי ללכת ובצד ימין כדי להסתכל.",
    walkHintTouch: "גררו בצד שמאל כדי ללכת, ובצד ימין כדי להסתכל.",
    // Bubbles: the role names, the action and the locator are data; these are the frames around them.
    bubbleOpen: "פתיחת המקורות: {title}",
    bubbleCount: "{n} דמויות",
    bubbleCountUnstated: "מספר לא נאמר במקור",
    bubbleCapped: "מוצגות {shown} מתוך {total}",
    bubbleUnplaced: "המקום אינו מצויר במודל",
    // L-04: a raised piece (the altar, the ramp, a chamber inside a building): no surface is drawn for figures to stand on.
    bubbleRaised: "המקום מצויר כמבנה מוגבה או סגור; דמויות אינן מוצגות בו",
    bubblePairsMore: "ועוד {n} משתתפים — ראו מקורות",
    bubbleInferred: "מקום מוסק",
    bubbleMore: "ועוד {n} אירועים בשלב זה",
    legendTitle: "הבוקר החי: מה מבוסס ומה המחשה",
    legend: "מבוסס על הרשומות (לפי משנה תמיד ומקורות נוספים, ברמת הוודאות שבכל רשומה): אילו אירועים מתרחשים ובאיזה סדר, היכן, מי משתתף וכמה. המחשה בלבד: משך כל שלב, מסלולי ההליכה ומהירותה, תנועת הדמויות, מקומן בתוך החלק, צורת הדמויות וגוונן האחיד, האש והעשן. הדמויות אינן מראות כיצד נעשתה פעולה כלשהי: אין להן תנוחה או מחווה, ועיגול לרגליהן מסמן רק שהן משתתפות באירוע. דמות מוצגת רק בזמן אירוע שהיא משתתפת בו, או בהליכה בין שני אירועים שלה. אירוע שמקומו אינו מצויר במודל מוצג בתווית בלבד, בלי דמויות. מסלול אינו עובר במקום שכלל גישה אוסר על התפקיד, ואינו נכנס לבניין, לפתח או לחדר: לשם הדמות מופיעה בלי הליכה.",
    figuresLegend: "דמויות: גוף אחיד בגוון אפור אחד, בלי פנים, כלים, עיטור או בגד מסוים; פס צבע במותניים מבחין בין תפקידים בלבד, ושם התפקיד כתוב בתווית. מספר הדמויות הוא המספר שבמקור, עד תקרת תצוגה שמצוינת בתווית; עיגול רחב על הקרקע מסמן קבוצה שמספרה לא נאמר במקור.",
    lightLegend: "האור קבוע ואינו משתנה עם ההצגה: אין בו טענה על שעה, על עלות השחר או על כיוון השמש. האש והעשן על המזבח קבועים לאורך כל ההצגה ואינם מגיבים לשלבים. אין בהצגה קול.",
    orderLegend: "סדר חמשת הרצפים זה אחר זה הוא קריאה של הפרויקט בסדר הסיפור במשנה; בתחילת כל רצף מוצגת ההערה שבנתונים על המשכו.",
    conditionalLegend: "שלבים שהמקור מתאר רק בתנאי מסוים (כהן גדול, שבת) אינם מוצגים בדמויות כברירת מחדל; הכפתור „שלבים מותנים” מציג אותם, עם סימון „מותנה”. כשיש באירוע קריאות חלופיות, הדמויות אינן הולכות אליו אלא מופיעות במקומן.",
    reduced: "התנועה מצומצמת לפי הגדרות המכשיר: ההצגה מתחילה מושהית, הדמויות מופיעות במקומן בלי הליכה, והאש והעשן אינם נעים.",
    conditionalToggle: "שלבים מותנים",
    conditionalToggleLabel: "הצגת דמויות גם בשלבים שהמקור מתאר רק בתנאי מסוים (כהן גדול, שבת)",
    conditionalHidden: "שלב זה מתואר במקור רק בתנאי מסוים, ולכן אינו מוצג כחלק מהמהלך היומי ודמויותיו אינן מוצגות. „שלבים מותנים” מציג אותן.",
    conditionalShown: "מותנה: מוצגות גם דמויות של שלבים שהמקור מתאר רק בתנאי מסוים.",
    sharedSlot: "{n} אירועים באותו שלב; סדרם אינו נאמר.",
    alternativeOpen: "קריאה חלופית — לא הוכרע",
    sources: "מקורות",
    sourcesLabel: "פתיחת המקורות של האירוע שבשלב הנוכחי",
    locatorPrefix: "לפי {locator}",
    gateException: "לפי כלל הגישה „{place}” אסור עבור „{persona}”, אבל הרשומה מציינת חריג, ולכן אין כאן חסימה: {exception}",
    intro: "הבוקר רץ לפני עיניכם: סדר השלבים, מקומם ומשתתפיהם — לפי הרשומות; התנועה, המשכים והמראה — המחשה.",
    introLegend: "מה מבוסס ומה המחשה",
    introDismiss: "הבנתי",
    // The live HUD cannot change the day type (the text page can), so its chip only names the viewing assumption.
    dayChip: "הנחת צפייה: {label}",
    notesMore: "עוד",
    notesLess: "פחות",
    emptyDayType: "לסוג היום שנבחר אין ברשומות שלבים בבוקר הזה, ולכן אין כאן דמויות. סוג היום נבחר בדף הטקסט."
  },
  licences: {
    button: "מקורות ורישיונות",
    title: "מקורות ורישיונות",
    close: "סגירה",
    intro: "הציטוטים באתר מובאים מטקסטים שהועתקו אל הפרויקט, ולכל טקסט כאן מצוינים המקור והרישיון שלו.",
    textsHeading: "הטקסטים המצוטטים",
    omissionNote: "התרגום האנגלי של המשנה מאת ד״ר יהושע קולפ (Mishnah Yomit) אינו מוצג באתר הציבורי: הרישיון טרם אושר בידי בעל הזכויות. הציטוטים בעברית והטענות עצמן מוצגים כרגיל.",
    noTexts: "לא נטענו טקסטים מצוטטים.",
    unchanged: "הטקסט מובא ללא שינוי",
    licenceLabel: "רישיון",
    attributionLabel: "ייחוס",
    textIdLabel: "מזהה הטקסט",
    unknownLicence: "לא צוין",
    licenceLink: "נוסח הרישיון",
    projectHeading: "הפרויקט",
    content: "תוכן הפרויקט (רשומות, ניסוחים ותיאורים): CC BY-SA 4.0",
    code: "קוד הפרויקט: MIT",
    three: "Three.js (נטען מהעותק המצורף): MIT",
    filesHeading: "קבצי הרישיון וההודעות",
    fileCode: "LICENSE (קוד)",
    fileContent: "LICENSE-CONTENT.md (תוכן)",
    fileNotice: "NOTICE.md (הודעות צד שלישי)",
    fileThree: "Three.js — LICENSE"
  },
  footer: {
    note: "התוכן ההיסטורי בממשק נלקח מרשומות הנתונים בלבד; ראו מקור ורמת ביסוס לכל אירוע. כשאין נתונים — מוצג מצב ריק."
  }
});

export default strings;
